name: 😵‍💫 Sanity checks
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
permissions:
  pull-requests: write

jobs:
  test:
    name: 🧪 Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v2

      - name: 🏗 Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.3.1

      - name: 🏗 Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: pnpm

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🧪 Run tests
        run: pnpm run test

  lint:
    name: 👮‍♂️ Linters and formatters
    runs-on: ubuntu-latest
    permissions:
      checks: write # Allow creating checks
      contents: read
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v2

      - name: 🏗 Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.3.1

      - name: 🏗 Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: pnpm

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 👮‍♂️ Run linters
        run: pnpm run lint

      - name: 💅 Run fixers, and check diff
        id: diffCheck
        run: pnpm run fix && git diff --exit-code -- ':!yarn.lock'

      - name: 💬 Post a check explaining the issue
        if: ${{ failure() && steps.diffCheck.conclusion == 'failure' }}
        uses: LouisBrunner/checks-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: 🧹 Check all files are formatted correctly
          conclusion: failure
          output: |
            {"summary": "Hrm, seems like you don't have prettier set up properly. Make sure your editor is configured to format code automatically, and that it respects the project's prettier config. [Click here](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) to view the Prettier extension for VS Code.\n\n> _**💡 Tip:**_ \n> \n> In the meantime you can run `npm run fix` and commit the changes."}
